option -h introduced with usage function

diff --git a/iptables-optimizer b/iptables-optimizer
--- a/iptables-optimizer
+++ b/iptables-optimizer
@@ -3,7 +3,7 @@
 # License:  GNU General Public License version 3 or newer
 # Author:   Johannes Hubertz <johannes@hubertz.de>
 # Version:  0.9.10
-# Date:     2014-08-18
+# Date:     2014-09-01
 #
 # Fullname: /usr/sbin/iptables-optimizer
 #
@@ -14,6 +14,8 @@
 #
 #    -c    if present, no resetting the paket/byte counters
 #          for easier long term debugging
+#
+#    -h    hint for options
 #
 #    -i    verbose logging reduced to INPUT and OUTPUT chains
 #
@@ -88,13 +90,14 @@ set -o pipefail
 #
 # evaluate command line arguments
 #
-while getopts ":acvw" opt; do
+while getopts ":achvw" opt; do
   case $opt in
     a) AUTO=${AUTO__DIR}/unwanted ;;
     c) COUNTER=1;;
+    h) usage; exit 1;;
     v) VERBLOG=$(( ${VERBLOG} + 1 ));;
     w) INOUT=$TRUE; VERBLOG=2;;
-    \?) echo "Invalid option: -$OPTARG" >&2 ; exit 1;;
+    \?) echo "invalid option -- $OPTARG" >&2 ; usage; exit 1;;
   esac
 done
 ###############################################
